In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraries imported Successfully!")

Libraries imported Successfully!

In [4]:
customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

In [5]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order Items: (112650, 7)
Payments: (103886, 5)
Reviews: (99224, 7)
Products: (32951, 9)
Sellers: (3095, 4)
Category Translation: (71, 2)

In [7]:
print("Customers Columns:",customers.columns.tolist())
print("\nOrders Columns:",orders.columns.tolist())
print("\nOrder Items Columns:",order_items.columns.tolist())
print("\nPayments Columns:",payments.columns.tolist())
print("\nReviews Columns:",reviews.columns.tolist())
print("\nProducts Columns:",products.columns.tolist())
print("\nSellers Columns:",sellers.columns.tolist())

Customers Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Orders Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Order Items Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Payments Columns: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Reviews Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Products Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Sellers Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [8]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [9]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [10]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [13]:
tables = {
    "Customers":customers,
    "Orders": orders,
    "Order Items":order_items,
    "Payemnts":payments,
    "Reviews":reviews,
    "Products":products,
    "Sellers":sellers,
    "Category Transalation":category_translation
}

for name,df in tables.items():
    print(f"\n{name}")
    print("-"*len(name))
    print(df.dtypes)

Customers
---------
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

Orders
------
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

Order Items
-----------
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

Payemnts
--------
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

Reviews
-------
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

Products
--------
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Sellers
-------
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

Category Transalation
---------------------
product_category_name            object
product_category_name_english    object
dtype: object

In [14]:
for name, df in tables.items():
    print(f"\n{name}")
    print("-" * len(name))
    print(df.isnull().sum())

Customers
---------
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Orders
------
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Order Items
-----------
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Payemnts
--------
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Reviews
-------
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Products
--------
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Sellers
-------
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Category Transalation
---------------------
product_category_name            0
product_category_name_english    0
dtype: int64

In [15]:
print("Orders with missing carrier date:")
print(
    orders[orders["order_delivered_carrier_date"].isnull()]
    ["order_status"]
    .value_counts()
)

print("\nOrders with missing customer delivery date:")
print(
    orders[orders["order_delivered_customer_date"].isnull()]
    ["order_status"]
    .value_counts()
)

Orders with missing carrier date:
order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

Orders with missing customer delivery date:
order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [16]:
print("Review Score Missing Values:")
print(reviews["review_score"].isnull().sum())

print("\nReview Score Distribution:")
print(reviews["review_score"].value_counts().sort_index())

Review Score Missing Values:
0

Review Score Distribution:
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [17]:
print("Missing values in Products:")
print(products.isnull().sum())

print("\nProducts with missing category:")
print(products[products["product_category_name"].isnull()].head())

print("\nProducts with missing physical attributes:")
print(
    products[
        products[
            ["product_weight_g",
             "product_length_cm",
             "product_height_cm",
             "product_width_cm"]
        ].isnull().any(axis=1)
    ]
)

Missing values in Products:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Products with missing category:
                           product_id product_category_name  \
105  a41e356c76fab66334f36de622ecbd3a                   NaN
128  d8dee61c2034d6d075997acef1870e9b                   NaN
145  56139431d72cd51f19eb9f7dae4d1617                   NaN
154  46b48281eb6d663ced748f324108c733                   NaN
197  5fb61f482620cb672f5e586bb132eae9                   NaN

     product_name_lenght  product_description_lenght  product_photos_qty  \
105                  NaN                         NaN                 NaN
128                  NaN                         NaN                 NaN
145                  NaN                         NaN                 NaN
154                  NaN                         NaN                 NaN
197                  NaN                         NaN                 NaN

     product_weight_g  product_length_cm  product_height_cm  product_width_cm
105             650.0               17.0               14.0              12.0
128             300.0               16.0                7.0              20.0
145             200.0               20.0               20.0              20.0
154           18500.0               41.0               30.0              41.0
197             300.0               35.0                7.0              12.0

Products with missing physical attributes:
                             product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes
18851  5eb564652db742ff8f28759cd8d2652a                   NaN

       product_name_lenght  product_description_lenght  product_photos_qty  \
8578                  60.0                       865.0                 3.0
18851                  NaN                         NaN                 NaN

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN
18851               NaN                NaN                NaN

       product_width_cm
8578                NaN
18851               NaN

In [18]:
for name ,df in tables.items():
    print(f"{name}:{df.duplicated().sum()}duplicate rows")

Customers:0duplicate rows
Orders:0duplicate rows
Order Items:0duplicate rows
Payemnts:0duplicate rows
Reviews:0duplicate rows
Products:0duplicate rows
Sellers:0duplicate rows
Category Transalation:0duplicate rows

In [19]:
for name ,df in tables.items():
    print(f"{name}:{df.shape[0]} rows,{df.shape[1]}columns")

Customers:99441 rows,5columns
Orders:99441 rows,8columns
Order Items:112650 rows,7columns
Payemnts:103886 rows,5columns
Reviews:99224 rows,7columns
Products:32951 rows,9columns
Sellers:3095 rows,4columns
Category Transalation:71 rows,2columns

In [20]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)
orders["order_approved_at"] = pd.to_datetime(
    orders["order_approved_at"]
)
orders["order_delivered_carrier_date"] = pd.to_datetime(
    orders["order_delivered_carrier_date"]
)
orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"]
)
orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"]
)
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)
reviews["review_creation_date"] = pd.to_datetime(
    reviews["review_creation_date"]
)
reviews["review_answer_timestamp"] = pd.to_datetime(
    reviews["review_answer_timestamp"]
)

In [21]:
print("Orders date columns:")
print(orders.dtypes)

print("\nOrder Items date column:")
print(order_items["shipping_limit_date"].dtype)

print("\nReviews date columns:")
print(reviews.dtypes)

Orders date columns:
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

Order Items date column:
datetime64[ns]

Reviews date columns:
review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [22]:
reviews["review_comment_title"] = reviews["review_comment_title"].fillna("No Comment")
reviews["review_comment_message"] = reviews["review_comment_message"].fillna("No Comment")

In [23]:
products["product_category_name"] = products["product_category_name"].fillna("Unknown")

In [24]:
print("Missing values after cleaning:")

print("\nReviews:")
print(reviews[["review_comment_title", "review_comment_message"]].isnull().sum())

print("\nProducts:")
print(products["product_category_name"].isnull().sum())

Missing values after cleaning:

Reviews:
review_comment_title      0
review_comment_message    0
dtype: int64

Products:
0

In [25]:
print("FINAL DATASET VALIDATION")
print("=" * 40)

for name, df in tables.items():
    print(f"\n{name}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

FINAL DATASET VALIDATION
========================================

Customers
Rows: 99441
Columns: 5
Missing values: 0
Duplicate rows: 0

Orders
Rows: 99441
Columns: 8
Missing values: 4908
Duplicate rows: 0

Order Items
Rows: 112650
Columns: 7
Missing values: 0
Duplicate rows: 0

Payemnts
Rows: 103886
Columns: 5
Missing values: 0
Duplicate rows: 0

Reviews
Rows: 99224
Columns: 7
Missing values: 0
Duplicate rows: 0

Products
Rows: 32951
Columns: 9
Missing values: 1838
Duplicate rows: 0

Sellers
Rows: 3095
Columns: 4
Missing values: 0
Duplicate rows: 0

Category Transalation
Rows: 71
Columns: 2
Missing values: 0
Duplicate rows: 0

In [26]:
tables = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Reviews": reviews,
    "Products": products,
    "Sellers": sellers,
    "Category Translation": category_translation
}

In [27]:
for name, df in tables.items():
    print(f"{name}: {len(df)} rows, {len(df.columns)} columns")

Customers: 99441 rows, 5 columns
Orders: 99441 rows, 8 columns
Order Items: 112650 rows, 7 columns
Payments: 103886 rows, 5 columns
Reviews: 99224 rows, 7 columns
Products: 32951 rows, 9 columns
Sellers: 3095 rows, 4 columns
Category Translation: 71 rows, 2 columns